name: Rinks Alphabetical

on:
  pull_request:
  push:
    branches: master

jobs:
  test-rinks-alphabetical:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run Tests
        run: python tests/rinks-alphabetical.py
